USE REALSTATE_Project;
GO

-- ROLES
INSERT INTO USUARIO_ROLES(NOMBRE,DESCRIPCION) VALUES ('ADMIN','ROL CON TODOS LOS PROVILEGIOS');
INSERT INTO USUARIO_ROLES(NOMBRE,DESCRIPCION) VALUES ('USUARIO','ROL CON ALGUNOS DE LOS PROVILEGIOS');
GO

-- PAISES
INSERT INTO PAISES (NOMBRE) VALUES ('COSTA RICA');
INSERT INTO PAISES (NOMBRE) VALUES ('PANAMA');
GO

-- PROVINCIAS
INSERT INTO PROVINCIAS (NOMBRE) VALUES ('SAN JOSE');
INSERT INTO PROVINCIAS (NOMBRE) VALUES ('ALAJUELA');
INSERT INTO PROVINCIAS (NOMBRE) VALUES ('HEREDIA');
INSERT INTO PROVINCIAS (NOMBRE) VALUES ('CARTAGO');
INSERT INTO PROVINCIAS (NOMBRE) VALUES ('GUANACASTE');
INSERT INTO PROVINCIAS (NOMBRE) VALUES ('PUNTARENAS');
INSERT INTO PROVINCIAS (NOMBRE) VALUES ('LIMON');
GO

-- DIRECCIONES USUARIOS
INSERT INTO USUARIO_DIRECCIONES (DIRECCION_EXACTA, ID_PAIS_FK, ID_PROVINCIA_FK, CANTON, DISTRITO)
     VALUES ('1KM AL OESTE DE TRANSPORTES SANTA CECILIA', 1, 1, 'ACOSTA', 'SAN IGNACIO');
GO

-- USUARIOS
INSERT INTO USUARIOS (NOMBRE, APELLIDOS, EMAIL, TELEFONO, CONTRASENNA, ID_ROL_FK, ID_DIRECCION_FK)
     VALUES
           ('LUIS',
           'CASCANTE CALDERON',
           'LCASCANTE50329@UFIDE.AC.CR',
           '84848484',
           '50329',
           1,
           1);
GO

-- TIPO PROPIEDADES
INSERT INTO PROPIEDAD_TIPOS (NOMBRE, DESCRIPCION) VALUES ('MANSION', 'MASION');
INSERT INTO PROPIEDAD_TIPOS (NOMBRE, DESCRIPCION) VALUES ('CASA', 'CASA');
GO

-- DIRECCIONES PROPIEDADES
INSERT INTO PROPIEDAD_DIRECCIONES (DIRECCION_EXACTA, GMAPS_LINK , ID_PAIS_FK, ID_PROVINCIA_FK, CANTON, DISTRITO)
     VALUES ('COSTADO NORTE DE ESCUELA DE CORRALAR', 'https://goo.gl/maps/yq8DgW53ZuTNsxtb9', 1, 1, 'PALMICHAL', 'CORRALAR');
INSERT INTO PROPIEDAD_DIRECCIONES (DIRECCION_EXACTA, GMAPS_LINK , ID_PAIS_FK, ID_PROVINCIA_FK, CANTON, DISTRITO)
     VALUES ('Guapiles Centro', 'https://goo.gl/maps/yq8DgW53ZuTNsxtb9', 1, 2, 'Pococi', 'Cariari');
INSERT INTO PROPIEDAD_DIRECCIONES (DIRECCION_EXACTA, GMAPS_LINK, ID_PAIS_FK, ID_PROVINCIA_FK, CANTON, DISTRITO)
	VALUES ('Calle Principal 123', 'https://maps.link/property1', 1, 3, 'San José', 'Escazú');
INSERT INTO PROPIEDAD_DIRECCIONES (DIRECCION_EXACTA, GMAPS_LINK, ID_PAIS_FK, ID_PROVINCIA_FK, CANTON, DISTRITO)
	VALUES ('Calle Secundaria 321', 'https://maps.link/property4', 1, 4, 'Cartago', 'Cartago');
INSERT INTO PROPIEDAD_DIRECCIONES (DIRECCION_EXACTA, GMAPS_LINK, ID_PAIS_FK, ID_PROVINCIA_FK, CANTON, DISTRITO)
	VALUES ('Avenida Central 456', 'https://maps.link/property2', 1, 5, 'Heredia', 'Heredia');
INSERT INTO PROPIEDAD_DIRECCIONES (DIRECCION_EXACTA, GMAPS_LINK, ID_PAIS_FK, ID_PROVINCIA_FK, CANTON, DISTRITO)
	VALUES ('Avenida Principal 789', 'https://maps.link/property3', 1, 6, 'Alajuela', 'Alajuela');
go

-- DETALLES PROPIEDAD
INSERT INTO PROPIEDAD_DETALLES (CANTIDAD_BANNOS, CANTIDAD_CUARTOS, CANTIDAD_PARQUEO, CANTIDAD_METROS2)
     VALUES (2,5,2,500);
INSERT INTO PROPIEDAD_DETALLES (CANTIDAD_BANNOS, CANTIDAD_CUARTOS, CANTIDAD_PARQUEO, CANTIDAD_METROS2)
	VALUES (2, 3, 2, 180);
INSERT INTO PROPIEDAD_DETALLES (CANTIDAD_BANNOS, CANTIDAD_CUARTOS, CANTIDAD_PARQUEO, CANTIDAD_METROS2)
	VALUES (3, 4, 3, 250);
INSERT INTO PROPIEDAD_DETALLES (CANTIDAD_BANNOS, CANTIDAD_CUARTOS, CANTIDAD_PARQUEO, CANTIDAD_METROS2)
	VALUES (4, 5, 2, 300);
INSERT INTO PROPIEDAD_DETALLES (CANTIDAD_BANNOS, CANTIDAD_CUARTOS, CANTIDAD_PARQUEO, CANTIDAD_METROS2)
	VALUES (2, 3, 1, 150);
INSERT INTO PROPIEDAD_DETALLES (CANTIDAD_BANNOS, CANTIDAD_CUARTOS, CANTIDAD_PARQUEO, CANTIDAD_METROS2)
	VALUES (2, 4, 2, 160);
GO

-- PROPIEDAD
INSERT INTO PROPIEDADES (NOMBRE,DESCRIPCION,PRECIO,ESTADO,ID_TIPO_FK,ID_USUARIO_FK, ID_DETALLE_FK,ID_DIRECCION_FK)
    VALUES ('Casa en las tablas', 'Hermosa casa en corralar de mora', 99000000, 1, 2, 1, 1, 1);
INSERT INTO PROPIEDADES (NOMBRE, DESCRIPCION, PRECIO, ESTADO, ID_TIPO_FK, ID_USUARIO_FK, ID_DETALLE_FK, ID_DIRECCION_FK)
	VALUES ('Casa de Playa', 'Hermosa casa cerca de la playa', 150000, 1, 1, 1, 2, 2);
INSERT INTO PROPIEDADES (NOMBRE, DESCRIPCION, PRECIO, ESTADO, ID_TIPO_FK, ID_USUARIO_FK, ID_DETALLE_FK, ID_DIRECCION_FK)
	VALUES ('Apartamento de Lujo', 'Moderno apartamento en zona exclusiva', 300000, 1, 1, 1, 3, 3);
INSERT INTO PROPIEDADES (NOMBRE, DESCRIPCION, PRECIO, ESTADO, ID_TIPO_FK, ID_USUARIO_FK, ID_DETALLE_FK, ID_DIRECCION_FK)
	VALUES ('Terreno Amplio', 'Terreno para construcción', 80000, 1, 2, 1, 4, 4);
INSERT INTO PROPIEDADES (NOMBRE, DESCRIPCION, PRECIO, ESTADO, ID_TIPO_FK, ID_USUARIO_FK, ID_DETALLE_FK, ID_DIRECCION_FK)
	VALUES ('Apartamento Moderno', 'Acogedor apartamento en zona céntrica', 180000, 1, 2, 1, 5, 5);
INSERT INTO PROPIEDADES (NOMBRE, DESCRIPCION, PRECIO, ESTADO, ID_TIPO_FK, ID_USUARIO_FK, ID_DETALLE_FK, ID_DIRECCION_FK)
	VALUES ('Apartamento Moderno 4', 'Acogedor apartamento en zona céntrica 5', 1800000, 1, 2, 1, 6, 6);
GO
        
-- Imagees propiedad
insert into  PROPIEDAD_IMAGENES (IMAGEN, ID_PROPIEDAD_FK)values ('/IMG/PROPIEDADES/1.jpg', 1);
insert into  PROPIEDAD_IMAGENES (IMAGEN, ID_PROPIEDAD_FK)values ('/IMG/PROPIEDADES/2.jpg', 1);
insert into  PROPIEDAD_IMAGENES (IMAGEN, ID_PROPIEDAD_FK)values ('/IMG/PROPIEDADES/3.jpg', 1);

insert into  PROPIEDAD_IMAGENES (IMAGEN, ID_PROPIEDAD_FK)values ('/IMG/PROPIEDADES/4.jpg', 2);
insert into  PROPIEDAD_IMAGENES (IMAGEN, ID_PROPIEDAD_FK)values ('/IMG/PROPIEDADES/5.jpg', 2);
insert into  PROPIEDAD_IMAGENES (IMAGEN, ID_PROPIEDAD_FK)values ('/IMG/PROPIEDADES/6.jpg', 2);

insert into  PROPIEDAD_IMAGENES (IMAGEN, ID_PROPIEDAD_FK)values ('/IMG/PROPIEDADES/7.jpg', 3);
insert into  PROPIEDAD_IMAGENES (IMAGEN, ID_PROPIEDAD_FK)values ('/IMG/PROPIEDADES/8.jpg', 3);
insert into  PROPIEDAD_IMAGENES (IMAGEN, ID_PROPIEDAD_FK)values ('/IMG/PROPIEDADES/9.jpg', 3);

insert into  PROPIEDAD_IMAGENES (IMAGEN, ID_PROPIEDAD_FK)values ('/IMG/PROPIEDADES/10.jpg', 4);
insert into  PROPIEDAD_IMAGENES (IMAGEN, ID_PROPIEDAD_FK)values ('/IMG/PROPIEDADES/11.jpg', 4);
insert into  PROPIEDAD_IMAGENES (IMAGEN, ID_PROPIEDAD_FK)values ('/IMG/PROPIEDADES/12.jpg', 4);

insert into  PROPIEDAD_IMAGENES (IMAGEN, ID_PROPIEDAD_FK)values ('/IMG/PROPIEDADES/13.jpg', 5);
insert into  PROPIEDAD_IMAGENES (IMAGEN, ID_PROPIEDAD_FK)values ('/IMG/PROPIEDADES/14.jpg', 5);
insert into  PROPIEDAD_IMAGENES (IMAGEN, ID_PROPIEDAD_FK)values ('/IMG/PROPIEDADES/15.jpg', 5);

insert into  PROPIEDAD_IMAGENES (IMAGEN, ID_PROPIEDAD_FK)values ('/IMG/PROPIEDADES/16.jpg', 6);
insert into  PROPIEDAD_IMAGENES (IMAGEN, ID_PROPIEDAD_FK)values ('/IMG/PROPIEDADES/17.jpg', 6);
insert into  PROPIEDAD_IMAGENES (IMAGEN, ID_PROPIEDAD_FK)values ('/IMG/PROPIEDADES/18.jpg', 6);

select * from PROPIEDAD_IMAGENES;