
 -- VISTA PARA OBTENER LA DIRECCION POR USUARIO
 USE REAL_STATE;
 GO

CREATE OR ALTER VIEW DIRECCION_COMPLETA_USUARIO 
AS 
	SELECT US.ID, UD.DIRECCION_EXACTA, PA.NOMBRE AS PAIS, PA.ID AS ID_PAIS, PR.NOMBRE AS PROVINCIA, PR.ID AS ID_PROVINCIA,
			CONCAT(UD.DIRECCION_EXACTA, ' ', PR.NOMBRE, ' ', PA.NOMBRE) AS DIRECCION_COMPLETA, ud.CANTON, ud.DISTRITO
	FROM USUARIOS US
	INNER JOIN USUARIO_DIRECCIONES UD 
	ON US.ID_DIRECCION_FK = UD.ID
	INNER JOIN PAISES PA
	ON UD.ID_PAIS_FK = PA.ID
	INNER JOIN PROVINCIAS PR
	ON UD.ID_PROVINCIA_FK = PR.ID;
GO

 -- VISTA PARA OBTENER LA DIRECCION POR PROPIEDAD
CREATE OR ALTER VIEW DIRECCION_COMPLETA_PROPIEDAD 
	AS  
	SELECT PD.ID, UD.DIRECCION_EXACTA, PA.NOMBRE AS PAIS, PR.NOMBRE AS PROVINCIA,
			CONCAT(UD.DIRECCION_EXACTA, ' ', PR.NOMBRE, ' ', PA.NOMBRE) AS DIRECCION_COMPLETA, ud.CANTON, ud.DISTRITO
	FROM PROPIEDADES PD
	INNER JOIN USUARIO_DIRECCIONES UD 
	ON PD.ID_DIRECCION_FK = UD.ID
	INNER JOIN PAISES PA
	ON UD.ID_PAIS_FK = PA.ID
	INNER JOIN PROVINCIAS PR
	ON UD.ID_PROVINCIA_FK = PR.ID;
GO

 -- VISTA PARA OBTENER TODOS LOS DATOS DE LA PROPIEDAD
CREATE OR ALTER VIEW DATOS_PROPIEDAD 
AS
	SELECT PR.ID, PR.NOMBRE, PR.DESCRIPCION, PR.PRECIO, PR.ESTADO, PT.ID AS ID_TIPO, PT.NOMBRE TIPO, US.ID ID_DUENNO, CONCAT(US.NOMBRE, ' ', US.APELLIDOS) AS NOMBRE_DUENNO,
			PD.CANTIDAD_BANNOS, PD.CANTIDAD_CUARTOS, PD.CANTIDAD_PARQUEO, PD.CANTIDAD_METROS2, P.NOMBRE AS PAIS, P.ID AS PAIS_ID, PRO.NOMBRE AS PROVINCIA, PRO.ID AS PROVINCIA_ID, DP.CANTON AS CANTON, DP.DISTRITO AS DISTRITO, DP.DIRECCION_EXACTA
	FROM PROPIEDADES PR
	INNER JOIN PROPIEDAD_TIPOS PT
	ON PR.ID_TIPO_FK = PT.ID
	INNER JOIN USUARIOS US
	ON PR.ID_USUARIO_FK = US.ID
	INNER JOIN PROPIEDAD_DETALLES PD
	ON PR.ID_DETALLE_FK = PD.ID
	INNER JOIN PROPIEDAD_DIRECCIONES as DP
	ON PR.ID_DIRECCION_FK= DP.ID
	INNER JOIN PAISES as P
	ON DP.ID_PAIS_FK = P.ID
	INNER JOIN PROVINCIAS as PRO
	ON DP.ID_PROVINCIA_FK = PRO.ID
GO

 -- VISTA PARA OBTENER TODOS LOS DATOS DEL USUARIO

CREATE OR ALTER VIEW DATOS_USUARIO
AS
	SELECT US.ID, US.NOMBRE, US.APELLIDOS, US.EMAIL, US.TELEFONO, IIF(US.ESTADO = 1, 'Activo', 'Inactivo') as ESTADO_TEXT, US.ESTADO ESTADO_ID,  UR.NOMBRE AS ROL, US.ID_ROL_FK AS ID_ROL,
			DC.DIRECCION_COMPLETA, DC.DIRECCION_EXACTA, dc.PROVINCIA, DC.ID AS ID_DIRECCION, dc.PAIS, DC.ID_PAIS, DC.ID_PROVINCIA, dc.CANTON, dc.DISTRITO
	FROM USUARIOS US
	INNER JOIN USUARIO_ROLES UR
	ON US.ID_ROL_FK = UR.ID
	INNER JOIN DIRECCION_COMPLETA_USUARIO DC
	ON US.ID = DC.ID; 
GO

CREATE OR ALTER VIEW [dbo].[DATOS_PROPIEDAD] 
AS
	SELECT PR.ID, PR.NOMBRE, PR.DESCRIPCION, PR.PRECIO, PR.ESTADO, PT.ID AS ID_TIPO, PT.NOMBRE TIPO, US.ID ID_DUENNO, CONCAT(US.NOMBRE, ' ', US.APELLIDOS) AS NOMBRE_DUENNO,
			PD.CANTIDAD_BANNOS, PD.CANTIDAD_CUARTOS, PD.CANTIDAD_PARQUEO, PD.CANTIDAD_METROS2, P.NOMBRE AS PAIS, P.ID AS PAIS_ID, PRO.NOMBRE AS PROVINCIA, PRO.ID AS PROVINCIA_ID, DP.CANTON AS CANTON, DP.DISTRITO AS DISTRITO, DP.DIRECCION_EXACTA
	FROM PROPIEDADES PR
	INNER JOIN PROPIEDAD_TIPOS PT
	ON PR.ID_TIPO_FK = PT.ID
	INNER JOIN USUARIOS US
	ON PR.ID_USUARIO_FK = US.ID
	INNER JOIN PROPIEDAD_DETALLES PD
	ON PR.ID_DETALLE_FK = PD.ID
	INNER JOIN PROPIEDAD_DIRECCIONES as DP
	ON PR.ID_DIRECCION_FK= DP.ID
	INNER JOIN PAISES as P
	ON DP.ID_PAIS_FK = P.ID
	INNER JOIN PROVINCIAS as PRO
	ON DP.ID_PROVINCIA_FK = PRO.ID
GO

CREATE OR ALTER VIEW DATOS_CITAS
AS
    SELECT PC.ID, 
           CONVERT(varchar, PC.FECHA_HORA, 101) AS Fecha, 
           SUBSTRING(CONVERT(varchar, PC.FECHA_HORA, 108), 1, 5) AS Hora,
           PC.ID_PROPIEDAD,
           P.NOMBRE AS PROPIEDAD,
           PC.ID_USUARIO,
           U.NOMBRE AS USUARIO
    FROM PROPIEDADES_CITAS PC
    INNER JOIN PROPIEDADES P ON P.ID = PC.ID_PROPIEDAD
    INNER JOIN USUARIOS U ON U.ID = PC.ID_USUARIO;
GO