-- ----------------------------------------- CRUD PAISES
-- INSERT
-- DROP PROCEDURE SP_INSERT_PAISES
 USE REAL_STATE;
 GO

 -- Storeproducedure Login

-- CREATE PROCEDURE ValidarUsuario
 --@CorreoElectronico NVARCHAR(70),
-- @Contrasenna NVARCHAR(10)
 --AS
 --BEGIN
 -- SELECT ConsecutivoUsuario,
    --     CorreoElectronico,
	--	 Estado,
  --FROM dbo.USUARIOS

  --WHERE @CorreoElectronico = @CorreoElectronico
  --AND Contrasenna = @Contrasenna

  --END




CREATE OR ALTER PROCEDURE SP_INSERT_PAISES
@NOMBRE NVARCHAR(50)
AS
BEGIN
    INSERT INTO PAISES (NOMBRE)
    VALUES (@NOMBRE)
END;
GO

-- SELECT
-- DROP PROCEDURE SP_SELECT_PAISES
CREATE OR ALTER PROCEDURE SP_SELECT_PAISES
AS
BEGIN
    SELECT * FROM PAISES
END;
GO

-- UPDATE
-- DROP PROCEDURE SP_UPDATE_PAISES
CREATE OR ALTER PROCEDURE SP_UPDATE_PAISES
@ID BIGINT,
@NOMBRE NVARCHAR(50)
AS
BEGIN
    UPDATE PAISES SET NOMBRE = @NOMBRE WHERE ID = @ID
END;
GO

-- DELETE
-- DROP PROCEDURE SP_DELETE_PAISES
CREATE OR ALTER PROCEDURE SP_DELETE_PAISES
@ID BIGINT
AS
BEGIN
    DELETE FROM PAISES WHERE ID = @ID
END;
GO

-- ----------------------------------------- CRUD PROVINCIAS

-- INSERT
-- DROP PROCEDURE SP_INSERT_PROVINCIAS
CREATE OR ALTER PROCEDURE SP_INSERT_PROVINCIAS
@NOMBRE NVARCHAR(50)
AS
BEGIN
    INSERT INTO PROVINCIAS (NOMBRE)
    VALUES (@NOMBRE)
END;
GO

-- SELECT
-- DROP PROCEDURE SP_SELECT_PROVINCIAS
CREATE OR ALTER PROCEDURE SP_SELECT_PROVINCIAS
AS
BEGIN
    SELECT * FROM PROVINCIAS
END;
GO

-- UPDATE
-- DROP PROCEDURE SP_UPDATE_PROVINCIAS
CREATE OR ALTER PROCEDURE SP_UPDATE_PROVINCIAS
@ID BIGINT,
@NOMBRE NVARCHAR(50)
AS
BEGIN
    UPDATE PROVINCIAS SET NOMBRE = @NOMBRE WHERE ID = @ID
END;
GO

-- DELETE
-- DROP PROCEDURE SP_DELETE_PROVINCIAS
CREATE OR ALTER PROCEDURE SP_DELETE_PROVINCIAS
@ID BIGINT
AS
BEGIN
    DELETE FROM PROVINCIAS WHERE ID = @ID
END;
GO

-- ----------------------------------------- CRUD USUARIO_DIRECCIONES

-- INSERT
-- DROP PROCEDURE SP_INSERT_USUARIO_DIRECCIONES
CREATE OR ALTER PROCEDURE SP_INSERT_USUARIO_DIRECCIONES
@DIRECCION_EXACTA NVARCHAR(255),
@ID_PAIS_FK BIGINT,
@ID_PROVINCIA_FK BIGINT,
@CANTON BIGINT,
@DISTRITO NVARCHAR(100)
AS
BEGIN
    INSERT INTO USUARIO_DIRECCIONES (DIRECCION_EXACTA, ID_PAIS_FK, ID_PROVINCIA_FK, CANTON, DISTRITO)
    VALUES (@DIRECCION_EXACTA, @ID_PAIS_FK, @ID_PROVINCIA_FK, @CANTON, @DISTRITO)
END;
GO

-- SELECT
-- DROP PROCEDURE SP_SELECT_USUARIO_DIRECCIONES
CREATE OR ALTER PROCEDURE SP_SELECT_USUARIO_DIRECCIONES
AS
BEGIN
    SELECT UD.ID, UD.DIRECCION_EXACTA, P.NOMBRE AS PAIS, PR.NOMBRE AS PROVINCIA, UD.CANTON AS CANTON, UD.DISTRITO AS DISTRITO
    FROM USUARIO_DIRECCIONES UD
    INNER JOIN PAISES P ON UD.ID_PAIS_FK = P.ID
    INNER JOIN PROVINCIAS PR ON UD.ID_PROVINCIA_FK = PR.ID
END;
GO

-- UPDATE
-- DROP PROCEDURE SP_UPDATE_USUARIO_DIRECCIONES
CREATE OR ALTER PROCEDURE SP_UPDATE_USUARIO_DIRECCIONES
@ID BIGINT,
@DIRECCION_EXACTA NVARCHAR(255),
@ID_PAIS_FK BIGINT,
@ID_PROVINCIA_FK BIGINT,
@CANTON BIGINT,
@DISTRITO NVARCHAR(100)
AS
BEGIN
    UPDATE USUARIO_DIRECCIONES SET DIRECCION_EXACTA = @DIRECCION_EXACTA, ID_PAIS_FK = @ID_PAIS_FK, ID_PROVINCIA_FK = @ID_PROVINCIA_FK, CANTON = @CANTON, DISTRITO = @DISTRITO WHERE ID = @ID
END;
GO

-- DELETE
-- DROP PROCEDURE SP_DELETE_USUARIO_DIRECCIONES
CREATE OR ALTER PROCEDURE SP_DELETE_USUARIO_DIRECCIONES
@ID BIGINT
AS
BEGIN
    DELETE FROM USUARIO_DIRECCIONES WHERE ID = @ID
END;
GO

-- ----------------------------------------- CRUD PROPIEDAD_DIRECCIONES

-- INSERT
-- DROP PROCEDURE SP_INSERT_PROPIEDAD_DIRECCIONES
CREATE OR ALTER PROCEDURE SP_INSERT_PROPIEDAD_DIRECCIONES
	@DIRECCION_EXACTA NVARCHAR(255),
	@GMAPS_LINK NVARCHAR(MAX),
	@ID_PAIS_FK BIGINT,
	@ID_PROVINCIA_FK BIGINT,
	@CANTON BIGINT,
	@DISTRITO NVARCHAR(100)
AS
BEGIN
	INSERT INTO PROPIEDAD_DIRECCIONES (DIRECCION_EXACTA, GMAPS_LINK, ID_PAIS_FK, ID_PROVINCIA_FK, CANTON, DISTRITO)
	VALUES (@DIRECCION_EXACTA, @GMAPS_LINK, @ID_PAIS_FK, @ID_PROVINCIA_FK, @CANTON, @DISTRITO)
END;
GO 

-- SELECT ALL
-- DROP PROCEDURE SP_SELECT_ALL_PROPIEDAD_DIRECCIONES
CREATE OR ALTER PROCEDURE SP_SELECT_ALL_PROPIEDAD_DIRECCIONES
AS
BEGIN
	SELECT PD.ID, PD.DIRECCION_EXACTA, PD.GMAPS_LINK, P.NOMBRE AS PAIS, PR.NOMBRE AS PROVINCIA, PD.CANTON AS CANTON, PD.DISTRITO AS DISTRITO
	FROM PROPIEDAD_DIRECCIONES PD
	INNER JOIN PAISES P ON PD.ID_PAIS_FK = P.ID
	INNER JOIN PROVINCIAS PR ON PD.ID_PROVINCIA_FK = PR.ID
	
	
END;
GO
-- SELECT BY ID
-- DROP PROCEDURE SP_SELECT_PROPIEDAD_DIRECCIONES_BY_ID
CREATE OR ALTER PROCEDURE SP_SELECT_PROPIEDAD_DIRECCIONES_BY_ID
	@ID BIGINT
AS
BEGIN
	SELECT PD.ID, PD.DIRECCION_EXACTA, PD.GMAPS_LINK, P.NOMBRE AS PAIS, PR.NOMBRE AS PROVINCIA, PD.CANTON AS CANTON, PD.DISTRITO AS DISTRITO
	FROM PROPIEDAD_DIRECCIONES PD
	INNER JOIN PAISES P ON PD.ID_PAIS_FK = P.ID
	INNER JOIN PROVINCIAS PR ON PD.ID_PROVINCIA_FK = PR.ID
	
	
	WHERE PD.ID = @ID
END;
GO
-- UPDATE
-- DROP PROCEDURE SP_UPDATE_PROPIEDAD_DIRECCIONES
CREATE OR ALTER PROCEDURE SP_UPDATE_PROPIEDAD_DIRECCIONES
	@ID BIGINT,
	@DIRECCION_EXACTA NVARCHAR(255),
	@GMAPS_LINK NVARCHAR(MAX),
	@ID_PAIS_FK BIGINT,
	@ID_PROVINCIA_FK BIGINT,
	@CANTON BIGINT,
	@DISTRITO BIGINT
AS
BEGIN
	UPDATE PROPIEDAD_DIRECCIONES
	SET DIRECCION_EXACTA = @DIRECCION_EXACTA,
		GMAPS_LINK = @GMAPS_LINK,
		ID_PAIS_FK = @ID_PAIS_FK,
		ID_PROVINCIA_FK = @ID_PROVINCIA_FK,
		CANTON = @CANTON,
		DISTRITO = @DISTRITO
	WHERE ID = @ID;
END;
GO

-- DELETE
-- DROP PROCEDURE SP_DELETE_PROPIEDAD_DIRECCIONES
CREATE OR ALTER PROCEDURE SP_DELETE_PROPIEDAD_DIRECCIONES
	@ID BIGINT
AS
BEGIN
	DELETE FROM PROPIEDAD_DIRECCIONES
	WHERE ID = @ID;
END;
GO


-- ----------------------------------------- CRUD USUARIO_ROLES

-- INSERT
-- DROP PROCEDURE SP_INSERT_USUARIO_ROLES
CREATE OR ALTER PROCEDURE SP_INSERT_USUARIO_ROLES
@NOMBRE NVARCHAR(50),
@DESCRIPCION NVARCHAR(255)
AS
BEGIN
	INSERT INTO USUARIO_ROLES (NOMBRE, DESCRIPCION)
	VALUES (@NOMBRE, @DESCRIPCION)
END;
GO

-- SELECT
-- DROP PROCEDURE SP_SELECT_USUARIO_ROLES
CREATE OR ALTER PROCEDURE SP_SELECT_USUARIO_ROLES
AS
BEGIN
	SELECT *
	FROM USUARIO_ROLES
END;
GO

-- UPDATE
-- DROP PROCEDURE SP_UPDATE_USUARIO_ROLES
CREATE OR ALTER PROCEDURE SP_UPDATE_USUARIO_ROLES
@ID BIGINT,
@NOMBRE NVARCHAR(50),
@DESCRIPCION NVARCHAR(255)
AS
BEGIN
	UPDATE USUARIO_ROLES
	SET NOMBRE = @NOMBRE,
	DESCRIPCION = @DESCRIPCION
	WHERE ID = @ID
END;
GO

-- DELETE
-- DROP PROCEDURE SP_DELETE_USUARIO_ROLES
CREATE OR ALTER PROCEDURE SP_DELETE_USUARIO_ROLES
@ID BIGINT
AS
BEGIN
	DELETE FROM USUARIO_ROLES
	WHERE ID = @ID
END;
GO

-- ----------------------------------------- CRUD USUARIOS


-- ----------------------------------------- CRUD USUARIOS
-- INSERT 
-- DROP PROCEDURE SP_INSERT_USUARIO;
CREATE OR ALTER PROCEDURE SP_INSERT_USUARIO
	-- Datos Usuario
	@NOMBRE NVARCHAR(100),
	@APELLIDOS NVARCHAR(100),
	@EMAIL NVARCHAR(100),
	@TELEFONO NVARCHAR(100),
	@CONTRASENNA NVARCHAR(100),
	-- Datos Direccion Propiedad
	 @DireccionExacta nvarchar(255),
	 @IdPais bigint,
	 @IdProvincia bigint,
	 @Canton nvarchar(255),
	 @Distrito nvarchar(255)
AS
BEGIN
DECLARE @IDDIRECCION BIGINT
			-- INSERTA PROPIEDAD DIRECCIONES Y OBTIENE EL ID
	INSERT INTO [dbo].[USUARIO_DIRECCIONES]
           ([DIRECCION_EXACTA]
           ,[ID_PAIS_FK]
           ,[ID_PROVINCIA_FK]
		   ,[CANTON]
		   ,[DISTRITO])
     VALUES
           (@DireccionExacta, @IdPais, @IdProvincia, @Canton, @Distrito)
	SELECT  @IDDIRECCION = IDENT_CURRENT('USUARIO_DIRECCIONES');

	INSERT INTO USUARIOS (NOMBRE, APELLIDOS, EMAIL, TELEFONO, CONTRASENNA, ID_DIRECCION_FK)
	VALUES (@nombre, @apellidos, @email, @telefono, @contrasenna, @IDDIRECCION);
END;
GO
-- SELECT
-- DROP PROCEDURE SP_SELECT_USUARIOS
CREATE OR ALTER PROCEDURE SP_SELECT_USUARIOS
AS
BEGIN
	SELECT * FROM USUARIOS;
END;
GO

--Agregado por Hillary 
--SP para traer datos del usuario
CREATE OR ALTER PROCEDURE dbo.SP_SELECT_USUARIOS_TODO
AS
BEGIN
	SELECT * FROM DATOS_USUARIO
END;
GO


CREATE OR ALTER PROCEDURE SP_SELECT_PROPIEDADES_TODO
AS
BEGIN
	SELECT ID,
		  NOMBRE,
		  DESCRIPCION,
		  PRECIO,
		  IIF(ESTADO = 1, 'Activo', 'Inactivo') as ESTADO_TEXT,
		  TIPO,
		  ID_DUENNO,
		  NOMBRE_DUENNO,
		  CANTIDAD_BANNOS,
		  CANTIDAD_CUARTOS,
		  CANTIDAD_PARQUEO,
		  CANTIDAD_METROS2,
		  PAIS,
		  PROVINCIA,
		  CANTON,
		  DISTRITO,
		  DIRECCION_EXACTA

	  FROM dbo.DATOS_PROPIEDAD;
END;
GO

CREATE OR ALTER PROCEDURE SP_SELECT_SPECIFIC_USER
@ID BIGINT
AS
BEGIN
    SELECT [ID]
      ,[NOMBRE]
      ,[APELLIDOS]
      ,[EMAIL]
      ,[TELEFONO]
	  ,[ESTADO_ID]
      ,[ESTADO_TEXT]
      ,[ROL]
      ,[DIRECCION_COMPLETA]
      ,[DIRECCION_EXACTA]
      ,[PROVINCIA]
      ,[PAIS]
	  ,[CANTON]
	  ,[DISTRITO]
  FROM [dbo].[DATOS_USUARIO]
  WHERE ID = @ID
END;
GO

--select * from DATOS_USUARIO

--EXEC SP_SELECT_SPECIFIC_USER 1

CREATE OR ALTER PROCEDURE SP_INSERT_PROPIEDAD
	 -- Datos Propiedad
	 @Nombre nvarchar(100),   
     @Descripcion nvarchar(250),
	 @Precio decimal(12, 2),
	 -- Datos Tipo Propiedad
	 @IdTipo bigint,
	 -- Datos Duenno Propiedad
	 @IdUsuario bigint,
	 -- Datos Detalles Propiedad
	 @Cuartos bigint,
	 @Bannos bigint,
	 @Metros bigint,
	 @Parqueos bigint,
	 -- Datos Direccion Propiedad
	 @DireccionExacta nvarchar(255),
	 @IdPais bigint,
	 @IdProvincia bigint,
	 @Canton nvarchar(255),
	 @Distrito nvarchar(255),

	 -- Datos Ruta Imagenes Propiedad
	 @ImgRuta1 NVARCHAR(200),
	 @ImgRuta2 NVARCHAR(200),
	 @ImgRuta3 NVARCHAR(200),
	 @ImgRuta4 NVARCHAR(200)
AS
BEGIN
DECLARE @IDDIRECCION BIGINT, 
		@IDDETALLES BIGINT,
		@IDPROPIEDAD BIGINT
		-- INSERTA PROPIEDAD DIRECCIONES Y OBTIENE EL ID
INSERT INTO [dbo].[PROPIEDAD_DIRECCIONES]
           ([DIRECCION_EXACTA]
		   ,[GMAPS_LINK]
           ,[ID_PAIS_FK]
           ,[ID_PROVINCIA_FK]
		   ,[CANTON]
		   ,[DISTRITO])
     VALUES
           (@DireccionExacta, '123', @IdPais, @IdProvincia, @Canton, @Distrito)
	SELECT  @IDDIRECCION = IDENT_CURRENT('PROPIEDAD_DIRECCIONES');

	-- INSERTA PROPIEDAD_DETALLES Y OBTIENE EL ID
INSERT INTO [dbo].[PROPIEDAD_DETALLES]
           ([CANTIDAD_BANNOS]
           ,[CANTIDAD_CUARTOS]
           ,[CANTIDAD_PARQUEO]
           ,[CANTIDAD_METROS2])
     VALUES
           (@Bannos, @Cuartos, @Parqueos, @Metros)
	SELECT  @IDDETALLES = IDENT_CURRENT('PROPIEDAD_DETALLES');
	-- INSERTA PROPIEDADES Y OBTIENE EL ID
INSERT INTO [dbo].[PROPIEDADES]
           ([NOMBRE]
           ,[DESCRIPCION]
           ,[PRECIO]
           ,[ESTADO]
           ,[ID_TIPO_FK]
           ,[ID_USUARIO_FK]
           ,[ID_DETALLE_FK]
           ,[ID_DIRECCION_FK])
VALUES
           (@Nombre, @Descripcion, @Precio,'TRUE', @IdTipo, @IdUsuario, @IDDETALLES, @IDDIRECCION);
		   SELECT  @IDPROPIEDAD = IDENT_CURRENT('PROPIEDADES');

		   -- INSERTA LA IMAGEN 1 EN CASO DE NO SER NULA
	IF (@ImgRuta1 IS NOT NULL)
	BEGIN
INSERT INTO [dbo].[PROPIEDAD_IMAGENES]
           ([IMAGEN]
           ,[ID_PROPIEDAD_FK])
     VALUES
           (@ImgRuta1,@IDPROPIEDAD);
	END;
		   -- INSERTA LA IMAGEN 2 EN CASO DE NO SER NULA
	IF (@ImgRuta2 IS NOT NULL)
	BEGIN
INSERT INTO [dbo].[PROPIEDAD_IMAGENES]
           ([IMAGEN]
           ,[ID_PROPIEDAD_FK])
     VALUES
           (@ImgRuta2,@IDPROPIEDAD);
	END;
		   -- INSERTA LA IMAGEN 3 EN CASO DE NO SER NULA
	IF (@ImgRuta3 IS NOT NULL)
	BEGIN
INSERT INTO [dbo].[PROPIEDAD_IMAGENES]
           ([IMAGEN]
           ,[ID_PROPIEDAD_FK])
     VALUES
           (@ImgRuta3,@IDPROPIEDAD);
	END;
		   -- INSERTA LA IMAGEN 4 EN CASO DE NO SER NULA
	IF (@ImgRuta4 IS NOT NULL)
	BEGIN
		   INSERT INTO [dbo].[PROPIEDAD_IMAGENES]
           ([IMAGEN]
           ,[ID_PROPIEDAD_FK])
     VALUES
           (@ImgRuta4,@IDPROPIEDAD);
	END;
END;
GO
-- SELECT
-- DROP PROCEDURE SP_SELECT_PROPIEDAD_TIPOS
CREATE OR ALTER PROCEDURE SP_SELECT_PROPIEDAD_TIPOS
AS
BEGIN
    SELECT * FROM PROPIEDAD_TIPOS
END;
GO

-- SELECT
-- DROP PROCEDURE SP_SELECT_PROPIEDAD_IMAGENES
/*
CREATE OR ALTER PROCEDURE SP_SELECT_PROPIEDAD_IMAGENES
	@IDPROPIEDAD BIGINT
AS
BEGIN
    SELECT ROW_NUMBER() OVER(ORDER BY ID ASC) AS NumFila, IMAGEN, ID_PROPIEDAD_FK
    FROM PROPIEDAD_IMAGENES 
    WHERE ID_PROPIEDAD_FK = @IDPROPIEDAD;
END;
GO
*/
CREATE OR ALTER PROCEDURE SP_SELECT_PROPIEDAD_IMAGENES
	@IDPROPIEDAD BIGINT
AS
BEGIN
    SELECT *
    FROM PROPIEDAD_IMAGENES 
    WHERE ID_PROPIEDAD_FK = @IDPROPIEDAD;
END;
GO

--EXEC SP_SELECT_PROPIEDAD_IMAGENES 6

--EXEC SP_INSERT_PROPIEDAD 'Casa Roa', 'Casa de playa', 3000.50, 1, 1, 1, 1, 100, 2, 'San Rafael', 1, 3, 'AS', 'asd', 'asd.png', 'asd.png', null, null; 

--SP para editar la info de los usuarios 
CREATE OR ALTER PROCEDURE SP_UPDATE_USUARIOS
	 @Id bigint,
	 @Nombre nvarchar(100),   
     @Apellido nvarchar(100),
	 @Email nvarchar(100),
	 @Telefono nvarchar(100),
	 @IdRol bigint,
	 -- Direccion
	 @DireccionExacta nvarchar(200),
	 @Id_Pais bigint,
	 @Id_Provincia bigint,
	 @Canton nvarchar(200),
	 @Distrito nvarchar(200)
AS
BEGIN
DECLARE @IDDIRECCION BIGINT
SELECT @IDDIRECCION = ID_DIRECCION_FK FROM USUARIOS WHERE ID=@Id

UPDATE [dbo].[USUARIOS]
   SET [NOMBRE] = @Nombre
      ,[APELLIDOS] = @Apellido
      ,[EMAIL] =@Email
      ,[TELEFONO] = @Telefono
      ,[ID_ROL_FK] = @IdRol
 WHERE ID=@Id;

 UPDATE [dbo].[USUARIO_DIRECCIONES]
   SET [DIRECCION_EXACTA] = @DireccionExacta
      ,[ID_PAIS_FK] = @Id_Pais
      ,[ID_PROVINCIA_FK] = @Id_Provincia
	  , [CANTON] = @Canton
	  , [DISTRITO] = @Distrito
 WHERE ID=@IDDIRECCION;
 END;
GO


--EXEC SP_UPDATE_USUARIOS 1, "Pedro", "Martinez", "h@gmail.com", "8888-8888", 2, "Talamanca", 2, 2
--SELECT * FROM USUARIO_DIRECCIONES SELECT * FROM USUARIOS
-- ----------------------------------------- CRUD CITAS
-- INSERT
CREATE OR ALTER PROCEDURE SP_INSERT_PROPIEDADES_CITAS
	@IdPropiedad BIGINT,
	@IdUsuario BIGINT,
	@FechaHora DATETIME
AS
BEGIN
	INSERT INTO PROPIEDADES_CITAS (ID_PROPIEDAD, ID_USUARIO, FECHA_HORA)
	VALUES (@IdPropiedad, @IdUsuario, @FechaHora);
END;
GO
-- SELECT ALL
-- DROP PROCEDURE SP_SELECT_PROPIEDADES_CITAS_USUARIO
CREATE OR ALTER PROCEDURE SP_SELECT_PROPIEDADES_CITAS_USUARIO
	@IdUsuario BIGINT
AS
BEGIN
	SELECT * FROM PROPIEDADES_CITAS WHERE ID_USUARIO = @IdUsuario;
END;
GO

-- SELECT

CREATE OR ALTER PROCEDURE SP_SELECT_PROPIEDADES_CITAS_USUARIO
    @idUsuario bigint
AS
BEGIN
    SELECT * FROM DATOS_CITAS WHERE ID_USUARIO = @idUsuario;
END;
GO
-- UPDATE
CREATE OR ALTER PROCEDURE SP_UPDATE_PROPIEDADES_CITAS
	@Id BIGINT,
	@IdPropiedad BIGINT,
	@IdUsuario BIGINT,
	@FechaHora DATETIME
AS
BEGIN
	UPDATE PROPIEDADES_CITAS SET 
		ID_PROPIEDAD = @IdPropiedad,
		ID_USUARIO = @IdUsuario,
		FECHA_HORA = @FechaHora
	WHERE ID = @Id;
END;
GO
-- DELETE
CREATE OR ALTER PROCEDURE SP_DELETE_PROPIEDADES_CITAS
	@Id BIGINT
AS
BEGIN
	DELETE FROM PROPIEDADES_CITAS WHERE ID = @Id;
END;
GO

--UPDATE PROPIEDAD
--EXEC SP_UPDATE_PROPIEDAD 3, 'Casa Flores ROJAS', 'Casa bellisima', 380000, 1, 2, 3, 3, 375, 5, '600 norte de woods', 2, 2, 'SJ', 'SJ', '/img/propiedades/TESTACTUALIZAR2.jpg', 7, null, 0, '/img/propiedades/TESTINSERTAR3.jpg', 13, null, 0
-- SELECT * FROM PROPIEDADES
-- SELECT * FROM PROPIEDAD_DETALLES WHERE ID=3
-- SELECT * FROM PROPIEDAD_DIRECCIONES WHERE ID=5
-- SELECT * FROM PROPIEDAD_IMAGENES WHERE ID_PROPIEDAD_FK=3
CREATE OR ALTER PROCEDURE SP_UPDATE_PROPIEDAD
	 -- Datos Propiedad
	 @IdPropiedad bigint,
	 @Nombre nvarchar(100),   
     @Descripcion nvarchar(250),
	 @Precio decimal(12, 2),
	 -- Datos Tipo Propiedad
	 @IdTipo bigint,
	 -- Datos Duenno Propiedad
	 @IdUsuario bigint,
	 -- Datos Detalles Propiedad
	 @Cuartos bigint,
	 @Bannos bigint,
	 @Metros bigint,
	 @Parqueos bigint,
	 -- Datos Direccion Propiedad
	 @DireccionExacta nvarchar(255),
	 @IdPais bigint,
	 @IdProvincia bigint,
	 @Canton nvarchar(255),
	 @Distrito nvarchar(255),

	 -- Datos Ruta Imagenes Propiedad
	 @ImgRuta1 NVARCHAR(200),
	 @IdImg1 bigint,
	 @ImgRuta2 NVARCHAR(200),
	 @IdImg2 bigint,
	 @ImgRuta3 NVARCHAR(200),
	 @IdImg3 bigint,
	 @ImgRuta4 NVARCHAR(200),
	 @IdImg4 bigint
AS
BEGIN
DECLARE 

		@IDDIRECCION BIGINT, 
		@IDDETALLES BIGINT
		-- INSERTA PROPIEDAD DIRECCIONES Y OBTIENE EL ID
SELECT @IDDIRECCION = ID_DIRECCION_FK FROM PROPIEDADES WHERE ID=@IdPropiedad;
SELECT @IDDETALLES = ID_DETALLE_FK FROM PROPIEDADES WHERE ID=@IdPropiedad;

UPDATE [dbo].[PROPIEDADES]
   SET  [NOMBRE] = @Nombre
       ,[DESCRIPCION] = @Descripcion
       ,[PRECIO] = @Precio
       ,[ID_TIPO_FK] = @IdTipo
       ,[ID_USUARIO_FK] = @IdUsuario
 WHERE ID=@IdPropiedad;

 UPDATE [dbo].[PROPIEDAD_DIRECCIONES]
   SET  [DIRECCION_EXACTA] = @DireccionExacta
       ,[ID_PAIS_FK] = @IdPais
       ,[ID_PROVINCIA_FK] = @IdProvincia
	   ,[CANTON] = @Canton
	   ,[DISTRITO] = @Distrito
 WHERE ID=@IDDIRECCION;

 UPDATE [dbo].[PROPIEDAD_DETALLES]
   SET  [CANTIDAD_BANNOS] = @Bannos
		,[CANTIDAD_CUARTOS] = @Cuartos
        ,[CANTIDAD_PARQUEO] = @Parqueos
        ,[CANTIDAD_METROS2] = @Metros
 WHERE ID=@IDDETALLES;

	IF (@ImgRuta1 IS NOT NULL AND @IdImg1 IS NOT NULL)
	BEGIN
	UPDATE [dbo].[PROPIEDAD_IMAGENES]
     SET [IMAGEN] = @ImgRuta1
     WHERE ID_PROPIEDAD_FK=@IdPropiedad
	 AND ID = @IdImg1;
	END;
	IF (@ImgRuta2 IS NOT NULL AND @IdImg2 IS NOT NULL)
	BEGIN
	UPDATE [dbo].[PROPIEDAD_IMAGENES]
		 SET [IMAGEN] = @ImgRuta2
		 WHERE ID_PROPIEDAD_FK=@IdPropiedad
		 AND ID = @IdImg2;
	END;
	IF (@ImgRuta3 IS NOT NULL AND @IdImg3 IS NOT NULL)
	BEGIN
	UPDATE [dbo].[PROPIEDAD_IMAGENES]
		 SET [IMAGEN] = @ImgRuta3
		 WHERE ID_PROPIEDAD_FK=@IdPropiedad
		 AND ID = @IdImg3;
		END;
	IF (@ImgRuta4 IS NOT NULL AND @IdImg4 IS NOT NULL)
	BEGIN
	UPDATE [dbo].[PROPIEDAD_IMAGENES]
		 SET [IMAGEN] = @ImgRuta4
		 WHERE ID_PROPIEDAD_FK=@IdPropiedad
		 AND ID = @IdImg4;
		END;
	IF (@ImgRuta1 IS NOT NULL AND @IdImg1=0)
	BEGIN
		INSERT INTO [dbo].[PROPIEDAD_IMAGENES]
           ([IMAGEN]
           ,[ID_PROPIEDAD_FK])
     VALUES
           (@ImgRuta1,@IDPROPIEDAD);
	END;
	IF (@ImgRuta2 IS NOT NULL AND @IdImg2=0)
	BEGIN
		INSERT INTO [dbo].[PROPIEDAD_IMAGENES]
           ([IMAGEN]
           ,[ID_PROPIEDAD_FK])
     VALUES
           (@ImgRuta2,@IDPROPIEDAD);
	END;
	IF (@ImgRuta3 IS NOT NULL AND @IdImg3=0)
	BEGIN
		INSERT INTO [dbo].[PROPIEDAD_IMAGENES]
           ([IMAGEN]
           ,[ID_PROPIEDAD_FK])
     VALUES
           (@ImgRuta3,@IDPROPIEDAD);
	END;
	IF (@ImgRuta4 IS NOT NULL AND @IdImg4=0)
	BEGIN
		INSERT INTO [dbo].[PROPIEDAD_IMAGENES]
           ([IMAGEN]
           ,[ID_PROPIEDAD_FK])
     VALUES
           (@ImgRuta4,@IDPROPIEDAD);
	END;

END;
GO

--TRAER UNA PROPIEDAD EN ESPECIFICO 
CREATE OR ALTER PROCEDURE SP_SELECT_PROPIEDAD_ESPECIFICA
@ID BIGINT
AS
BEGIN
	SELECT ID,
		  NOMBRE,
		  DESCRIPCION,
		  PRECIO,
		  ESTADO as ESTADO_ID,
		  IIF(ESTADO = 1, 'Activo', 'Inactivo') as ESTADO_TEXT,
		  ID_TIPO,
		  TIPO,
		  ID_DUENNO,
		  NOMBRE_DUENNO,
		  CANTIDAD_BANNOS,
		  CANTIDAD_CUARTOS,
		  CANTIDAD_PARQUEO,
		  CANTIDAD_METROS2,
		  PAIS_ID,
		  PAIS,
		  PROVINCIA_ID,
		  PROVINCIA,
		  CANTON,
		  DISTRITO,
		  DIRECCION_EXACTA
	  FROM dbo.DATOS_PROPIEDAD
	  WHERE ID = @ID;
END;
GO
-- EXEC SP_SELECT_PROPIEDAD_ESPECIFICA 3

--Cambiar el estado de una propiedad 
-- SELECT * FROM PROPIEDADES WHERE ID=1
-- EXEC SP_UPDATE_ESTADO_PROPIEDAD 1

CREATE OR ALTER PROCEDURE SP_UPDATE_ESTADO_PROPIEDAD
@ID BIGINT
AS
BEGIN
DECLARE
@ESTADO INT
SELECT @ESTADO = P.ESTADO FROM PROPIEDADES P WHERE P.ID=@ID;

IF (@ESTADO = 1)
BEGIN
UPDATE [dbo].[PROPIEDADES]
	 SET [ESTADO] = 0
	 WHERE ID = @ID;
END;
IF (@ESTADO = 0)
BEGIN
UPDATE [dbo].[PROPIEDADES]
	 SET [ESTADO] = 1
	 WHERE ID = @ID;
END;
END;
GO

CREATE OR ALTER PROCEDURE SP_UPDATE_ESTADO_USUARIO
@ID BIGINT
AS
BEGIN
DECLARE
@ESTADO INT
SELECT @ESTADO = P.ESTADO FROM USUARIOS P WHERE P.ID=@ID;

 

IF (@ESTADO = 1)
BEGIN
UPDATE [dbo].[USUARIOS]
     SET [ESTADO] = 0
     WHERE ID = @ID;
END;
IF (@ESTADO = 0)
BEGIN
UPDATE [dbo].[USUARIOS]
     SET [ESTADO] = 1
     WHERE ID = @ID;
END;
END;
GO