USE REAL_STATE;
GO

-- ROLES
INSERT INTO USUARIO_ROLES(NOMBRE,DESCRIPCION) VALUES ('ADMIN','ROL CON TODOS LOS PROVILEGIOS');
INSERT INTO USUARIO_ROLES(NOMBRE,DESCRIPCION) VALUES ('USUARIO','ROL CON ALGUNOS DE LOS PROVILEGIOS');
GO

-- PAISES
INSERT INTO PAISES (NOMBRE) VALUES ('COSTA RICA');
INSERT INTO PAISES (NOMBRE) VALUES ('PANAMA');
GO

-- PROVINCIAS
INSERT INTO PROVINCIAS (NOMBRE) VALUES ('SAN JOSE');
INSERT INTO PROVINCIAS (NOMBRE) VALUES ('ALAJUELA');
INSERT INTO PROVINCIAS (NOMBRE) VALUES ('HEREDIA');
INSERT INTO PROVINCIAS (NOMBRE) VALUES ('CARTAGO');
INSERT INTO PROVINCIAS (NOMBRE) VALUES ('GUANACASTE');
INSERT INTO PROVINCIAS (NOMBRE) VALUES ('PUNTARENAS');
INSERT INTO PROVINCIAS (NOMBRE) VALUES ('LIMON');
GO
-- DIRECCIONES USUARIOS
INSERT INTO USUARIO_DIRECCIONES (DIRECCION_EXACTA, ID_PAIS_FK, ID_PROVINCIA_FK, CANTON, DISTRITO)
     VALUES ('1KM AL OESTE DE TRANSPORTES SANTA CECILIA', 1, 1, 'ACOSTA', 'SAN IGNACIO');
GO

-- USUARIOS
INSERT INTO USUARIOS (NOMBRE, APELLIDOS, EMAIL, TELEFONO, CONTRASENNA, ID_ROL_FK, ID_DIRECCION_FK)
     VALUES
           ('LUIS',
           'CASCANTE CALDERON',
           'LCASCANTE50329@UFIDE.AC.CR',
           '84848484',
           '50329',
           1,
           1);
GO

-- TIPO PROPIEDADES
INSERT INTO PROPIEDAD_TIPOS (NOMBRE, DESCRIPCION) VALUES ('MANSION', 'MASION');
INSERT INTO PROPIEDAD_TIPOS (NOMBRE, DESCRIPCION) VALUES ('CASA', 'CASA');
GO

-- DIRECCIONES PROPIEDADES
INSERT INTO PROPIEDAD_DIRECCIONES (DIRECCION_EXACTA, GMAPS_LINK , ID_PAIS_FK, ID_PROVINCIA_FK, CANTON, DISTRITO)
     VALUES ('COSTADO NORTE DE ESCUELA DE CORRALAR', 'https://goo.gl/maps/yq8DgW53ZuTNsxtb9', 1, 1, 'PALMICHAL', 'CORRALAR');
INSERT INTO PROPIEDAD_DIRECCIONES (DIRECCION_EXACTA, GMAPS_LINK , ID_PAIS_FK, ID_PROVINCIA_FK, CANTON, DISTRITO)
     VALUES ('Guapiles Centro', 'https://goo.gl/maps/yq8DgW53ZuTNsxtb9', 1, 7, 'Pococ�', 'Cariari');
GO

-- DETALLES PROPIEDAD
INSERT INTO PROPIEDAD_DETALLES (CANTIDAD_BANNOS, CANTIDAD_CUARTOS, CANTIDAD_PARQUEO, CANTIDAD_METROS2)
     VALUES(2,5,2,500)
GO

-- PROPIEDAD
INSERT INTO PROPIEDADES
           (NOMBRE,
           DESCRIPCION,
           PRECIO,
           ESTADO,
           ID_TIPO_FK,
           ID_USUARIO_FK,
           ID_DETALLE_FK,
           ID_DIRECCION_FK)
     VALUES
           ('CASA 1', 'Hermosa casa en corralar de mora', 99000000, 1, 2, 1, 1, 1);
GO
        
-- Imagees propiedad
insert into  PROPIEDAD_IMAGENES (IMAGEN, ID_PROPIEDAD_FK)values ('/IMG/PROPIEDADES/1.jpg', 1);
insert into  PROPIEDAD_IMAGENES (IMAGEN, ID_PROPIEDAD_FK)values ('/IMG/PROPIEDADES/2.jpeg', 1);
insert into  PROPIEDAD_IMAGENES (IMAGEN, ID_PROPIEDAD_FK)values ('/IMG/PROPIEDADES/3.jpg', 1);
